### PR TITLE
Added Python solution and approach for 0070 - Climbing Stairs.

### PR DESCRIPTION
**Pull request by radojicic23**
## Change Summary

The purpose of this PR is to add coding solution and approach in Python for the LeetCode [Climbing Stairs](https://leetcode.com/problems/climbing-stairs/) problem.

## Checklist

**If you haven't fulfilled the below requirements or even delete the entire checklist, your PR won't be reviewed and will be closed without notice.**

### General 

- [x] This Pull Request is all my own work. (You'll be blacklisted if you are caught for plagiarism.)
- [x] I've read [CONTRIBUTING.md](https://github.com/wingkwong/leetcode-the-hard-way/blob/main/CONTRIBUTING.md)
- [x] I've applied LaTex for all variables, formulas and time / space complexity instead of using backticks
- [x] I've started the app locally and verified all the content and all links (if applicable) are accessible correctly
- [x] I've included Complexity Analysis (Time Complexity & Space Complexity).
- [x] I've written my explanation well and it is easy to understand for beginners

### Solutions

- [x] I've read and followed the [Solution Template](https://github.com/wingkwong/leetcode-the-hard-way/blob/main/CONTRIBUTING.md#solution-template)
- [x] I've formatted my code well with [K&R Coding style](https://gist.github.com/jesseschalken/0f47a2b5a738ced9c845#why-kr)
- [x] I've confirmed that comments are put above each line rather than writing on the same line.
- [x] I've included a meaningful approach name for my solution. e.g. `## Approach 1: Two Pointers`.

### CODE REVIEW

**Review by wingkwong — CHANGES_REQUESTED** [review]
The explanation only explains the line purely, which is easy to understand. However, readers won't be able to understand the intuitive behind simply by reading that.

**Comment by radojicic23** [comment]
It's pretty straightforward and easy to understand. There is nothing mutch more I have to said and explain about this question but alright.

**Comment by wingkwong** [comment]
@radojicic23 I don't think so. The audience is the beginners. The idea of this project is to let them learn something from your solution with explanations. Your solution is well-optimised for beginners and they can't figure out without any guidance. At least you may start with the solution with O(N) space first and state what `dp[i]` represents and the DP transition assuming they don't have DP knowledge. Then you can show how to optimise it. This question is a good start for learning DP IMO.

**Comment by radojicic23** [comment]
Alright. I'll try with a drawing explanation, it's easier to understand.

**Comment by radojicic23** [comment]
How to put a drawing inside @wingkwong?

**Comment by wingkwong** [comment]
@radojicic23 drag the image to Github comment editor. It will generate a link. You can paste the generated result on the markdown.

**Comment by wingkwong** [comment]
1. Still, it doesn't explain why this could solve the problem. You just visualise the code while the intuitive is missing here. we understand "how" but we also need to know "why".
2. You may use an online free tool like draw.io for better drawing. For a moment, I misread P1 as P4 under 8.

**Comment by radojicic23** [comment]
I don't know how to explain this better because it's easy and really straightforward. This is like fibonacci sequence, I think that it can be put in the previous solution @wingkwong.

**Comment by wingkwong** [comment]
You may merge to the approach 1 and state the difference between the existing solution and yours. My previous comments are derived from a beginner though.

**Comment by radojicic23** [comment]
@wingkwong can I put the same explanation like above?

**Comment by wingkwong** [comment]
Just try to explain like I'm five. At least you can mention how to link this problem to fibonacci sequence. It may be easy for you but not for some people.

**Comment by radojicic23** [comment]
Alright, alright.😅 I'll get it done like this guy above with the first approach but in Python.

**Comment by radojicic23** [comment]
I want to say one more thing. You are doing great job with this book and it's great for everyone, especially for beginners! I am glad to be able to contribute and help.

**Comment by wingkwong** [comment]
Thanks a lot.

**Pull request merged**
