### PR TITLE
Changed Formula presentation

### PR DESCRIPTION
**Pull request by Dikshant09**

### CODE REVIEW

**Review by wingkwong — COMMENTED** [review]
I don't see much different except the the gap. I tend to group them together though. If you wanna change it, probably change all of them instead of just this group.

**Comment by Dikshant09** [comment]
Screenshot 2022-10-01 at 12 21 23 PM

This line doesn't make sense. 1N ??
1N - m * (k - 1) = 1N - 1 ? 

It will look better if we break it into lines. like this
Screenshot 2022-10-01 at 12 22 50 PM

The rest of them looks good.

**Comment by wingkwong** [comment]
@Dikshant09 May I know which browser and version you are using?

Here's what I see in latest Chrome.

image

**Comment by Dikshant09** [comment]
Google Chrome
Version 106.0.5249.91 (Official Build) (arm64)

Firefox
Version 105.0.1 (64-bit)

Safari
Version 16.0 (17614.1.25.9.10, 17614)

In all the above browsers, I get the same single-line formula.

**Comment by wingkwong** [comment]
Ok I'll take that then. Thanks for pointing out.

**Pull request merged**
