### PR TITLE
Added Tutorial For Doubly linked list

### LINKED ISSUE #60: Tutorial Writeup - Doubly Linked List
Markdown Path: `tutorials/basic-topics/doubly-linked-list.md`

- Overview
- Explanation with 1 ~ 2 LC problems
- Suggested Problems (See `arrays.md` as a reference for the format)

### PR DESCRIPTION
**Pull request by i-dipanshu**
Fixes #60 
Signed off by: Dipanshu

### CODE REVIEW

**Review by wingkwong — CHANGES_REQUESTED** [review]
1. Code format is bad. (e.g. indentation)
2. Don't rely on GFG tutorials. I found most of them are overcomplicated and some TCs are actually incorrect. 
3. As a reader, I can't see how I can use it in LC problems. Walk through some LC problems and try to map what you show.

**Comment by wingkwong** [comment]
Any updates?

**Comment by i-dipanshu** [comment]
Sorry For the delay 
been just busy with other things 
Will make the requested soon

**Comment by wingkwong** [comment]
Closing due to inactivity.

**Pull request closed without merging**
