### PR TITLE
solution: 0009-palindrome-number JS changes

### PR DESCRIPTION
**Pull request by vigneshshiv**
## Change Summary

Provide summary of changes with issue number if any.

## Checklist

**If you haven't fulfilled the below requirements, your PR won't be reviewed.**

### General 

- [x] Make sure you've read [CONTRIBUTING.md](https://github.com/wingkwong/leetcode-the-hard-way/blob/main/CONTRIBUTING.md) 
- [x] Make sure you've followed the template format
- [x] Make sure you've started the app locally and verified all the content and all links (if applicable) must be accessible correctly
- [x] Make sure you've applied LaTex for variables, formulas and time / space complexity instead of using backticks
- [x] Make sure you've formatted your code well (Code Block is rendered using `<Tabs/>`)
      Below is a C++ example. You can include multiple langs using `<TabItem/>` if necessary
      
````
<Tabs>

<TabItem value="cpp" label="C++">
<SolutionAuthor name="@YOUR_ALIAS"/>

```cpp
// Your code goes here
// Prefer K&R Coding style
```

</TabItem>

</Tabs>
````
- [ ] Make sure you've explained your code well (write comments above each line - not inline)
- [ ] Make sure you've written your explanation well and it is easy to understand for beginners
- [ ] Make sure you've included Time & Space Complexity Analysis
- [ ] Make sure you've included a meaningful approach name for your solution. Don't leave it blank. e.g. `## Approach 1: Two Pointers`.

### For Tutorial Articles

- [ ] Make sure you've explained your topic using 1 - 3 LC problems rather than using external problems. Solutions must be taken with explanations as well.
- [ ] Make sure you've provided suggested problems at the end using the given format. See [here](https://raw.githubusercontent.com/wingkwong/leetcode-the-hard-way/main/tutorials/math/number-theory/binary-exponentiation.md) as an example. If the target solution is not available, leave `solutionLink` blank.
- [ ] Make sure you've given credits / references if you use external resources. For an image, give credit under it. Otherwise, add a new section called References at the end (after Suggested Problems).

### CODE REVIEW

**Comment by vigneshshiv** [comment]
Won't be need for this solution, but it's good to use Object.is.

**Comment by wingkwong** [comment]
Suggest to add some content on what is the difference between `Object.is`, `==` and `===` so that people can learn from it.

**Comment by vigneshshiv** [comment]
@wingkwong I have added the reference in the code, snapshot here. 

In JavaScript, we have used `Object.is(..)` for value comparison, It's a ES6 feature and makes value comparisons in an even more strict fashion than the === comparison.

References from MDN and You Don't Know JS (Behind the scenes polyfills of `Object.is`). 

> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is

> https://github.com/getify/You-Dont-Know-JS/blob/1st-ed/es6%20%26%20beyond/ch6.md#objectis-static-function

> https://github.com/getify/You-Dont-Know-JS/blob/1st-ed/es6%20%26%20beyond/ch1.md#shimspolyfills

**Review by wingkwong — APPROVED** [review]

**Comment by wingkwong** [comment]
@vigneshshiv I approved it already. It is pending for merge now.

**Comment by vigneshshiv** [comment]
@wingkwong Thanks for the update!

**Pull request merged**
