### PR TITLE
segment-tree.md

### PR DESCRIPTION
**Pull request by Dikshant09**
Segment Tree: Point Update & Range update including lazy propagation.

### CODE REVIEW

**Review by wingkwong — CHANGES_REQUESTED** [review]
Prefer to put in `segment-tree.md` so that we can show a basic one and a complete one in the same page.

**Comment by Dikshant09** [comment]
File name changed to : segment-tree.md

**Comment by wingkwong** [comment]
@Dikshant09 Not the PR title. I mean the actual file. You added the content in `templates/complete-segment-tree.md`. What I mean is to put your content in `templates/segment-tree.md` which is an existing file I added yesterday.

**Comment by Dikshant09** [comment]
Should I put it on the top or at the end in ur `templates/segment-tree.md`?

**Comment by wingkwong** [comment]
At the end please. I'll fine tune the structure later.

**Comment by Dikshant09** [comment]
done

**Pull request closed without merging**
