### PR TITLE
Added Python solution for 0048 - Rotate Image.

### PR DESCRIPTION
**Pull request by radojicic23**
## Change Summary

The purpose of this PR is to add coding solution in Python for the LeetCode [Rotate Image](https://leetcode.com/problems/rotate-image/) problem.

## Checklist

**If you haven't fulfilled the below requirements or even delete the entire checklist, your PR won't be reviewed and will be closed without notice.**

### General 

- [x] This Pull Request is all my own work. (You'll be blacklisted if you are caught for plagiarism.)
- [x] I've read [CONTRIBUTING.md](https://github.com/wingkwong/leetcode-the-hard-way/blob/main/CONTRIBUTING.md)
- [x] I've applied LaTex for all variables, formulas and time / space complexity instead of using backticks
- [x] I've started the app locally and verified all the content and all links (if applicable) are accessible correctly
- [x] I've included Complexity Analysis (Time Complexity & Space Complexity).
- [x] I've written my explanation well and it is easy to understand for beginners

### Solutions

- [x] I've read and followed the [Solution Template](https://github.com/wingkwong/leetcode-the-hard-way/blob/main/CONTRIBUTING.md#solution-template)
- [x] I've formatted my code well with [K&R Coding style](https://gist.github.com/jesseschalken/0f47a2b5a738ced9c845#why-kr)
- [x] I've confirmed that comments are put above each line rather than writing on the same line.
- [x] I've included a meaningful approach name for my solution. e.g. `## Approach 1: Two Pointers`.

### CODE REVIEW

**Review by wingkwong — COMMENTED** [review]
Please help wrap C++ solution in `<TabItem value="cpp" label="C++">...</TabItem>` and put it inside the same `<Tabs>`.

**Review by wingkwong — CHANGES_REQUESTED** [review]
I mean same Tabs with different TabItem.

**Comment by radojicic23** [comment]
> I mean same Tabs with different TabItem.

I did 

> I mean same Tabs with different TabItem.

I already wrote value=cpp and label=C++ in your TabItem

**Comment by radojicic23** [comment]
Oh, sorry I saw that

**Review by wingkwong — APPROVED** [review]

**Pull request merged**
