### PR TITLE
Updated HeapSort.md

### PR DESCRIPTION
**Pull request by Abhinav-J05**
Solved #99

### CODE REVIEW

**Review by wingkwong — CHANGES_REQUESTED** [review]
1. Don't copy content from https://www.geeksforgeeks.org/heap-sort/
2. Walk through the algo with LC problems. Not just copy content from GFG and post a LC solution.
3. Run the app locally to verify instead of just writing on a markdown editor

**Comment by Abhinav-J05** [comment]
sure, let me make the changes.

**Comment by wingkwong** [comment]
Don't close it. Update your branch and the changes will be reflected in this PR. I need the history.

**Comment by Abhinav-J05** [comment]
sure, let me make the changes.

**Comment by wingkwong** [comment]
Don't close it. Update your branch and the changes will be reflected in this PR. I need the history.

**Comment by Abhinav-J05** [comment]
Hey @wingkwong I have updated the content of the file. Please have a look.

**Review by wingkwong — CHANGES_REQUESTED** [review]
1. Like I said before, run the app and verify locally first.

image

2. The code is super messy (the indentation and comment).  Format it well please.

3. Use LaTex for Big O notation.

**Comment by Abhinav-J05** [comment]
sure, i'll make the changes

**Comment by wingkwong** [comment]
any update?

**Comment by wingkwong** [comment]
Closing due to inactivity.

**Pull request closed without merging**
