### PR TITLE
Heap-Sort

### PR DESCRIPTION
**Pull request by i-am-SnehaChauhan**
#99
## Change Summary
Tutorial Write-up of Heap-Sort.
.

## Checklist

**If you haven't fulfilled the below requirements or even delete the entire checklist, your PR won't be reviewed and will be closed without notice. Regular contributors (with 10+ PRs) can skip this part.**

### General 

- [x] This Pull Request is all my own work. (You'll be blacklisted if you are caught for plagiarism.)
- [x] I've read [CONTRIBUTING.md](https://github.com/wingkwong/leetcode-the-hard-way/blob/main/CONTRIBUTING.md)
- [x] I've applied LaTex for all variables, formulas and time / space complexity instead of using backticks
- [x] I've started the app locally and verified all the content and all links (if applicable) are accessible correctly
- [x] I've included Complexity Analysis (Time Complexity & Space Complexity).
- [x] I've written my explanation well and it is easy to understand for beginners

### Tutorial

- [x] I've read and followed the [Tutorial Template](https://github.com/wingkwong/leetcode-the-hard-way/blob/main/CONTRIBUTING.md#tutorial-template)
- [ ] I've explained my topic well with 2 - 3 LC problems and no external problems are used. 
- [x] I've provided the full working solutions to the problems used in this tutorial.
- [ ] I've provided suggested problems at the end with the given format. See [here](https://raw.githubusercontent.com/wingkwong/leetcode-the-hard-way/main/tutorials/math/number-theory/binary-exponentiation.md) as an example. If the target solution is not available, leave `solutionLink` blank.
- [ ] I've given credits / references if I use external resources. (For an image, give credit under it. Otherwise, add a new section called References at the end (after Suggested Problems).)

### Solutions

- [x] I've read and followed the [Solution Template](https://github.com/wingkwong/leetcode-the-hard-way/blob/main/CONTRIBUTING.md#solution-template)
- [x] I've formatted my code well with [K&R Coding style](https://gist.github.com/jesseschalken/0f47a2b5a738ced9c845#why-kr)
- [ ] I've confirmed that comments are put above each line rather than writing on the same line.
- [ ] I've included a meaningful approach name for my solution. e.g. `## Approach 1: Two Pointers`.

### CODE REVIEW

**Review by wingkwong — CHANGES_REQUESTED** [review]
> I've explained my topic well with 2 - 3 LC problems and no external problems are used.

This is mandatory. Also your code should link to your explanation. It's not clean enough for beginners. 

Your code is almost same as the one in https://www.geeksforgeeks.org/heap-sort/ except the variable naming. Also it can tell by the exact same test case `{12, 11, 13, 5, 6, 7}` .

**Comment by i-am-SnehaChauhan** [comment]
This is Heap Sort, so the algorithm remains the same, right? For Heapify, do we need to follow the same process? However, the example I used, {0, 0, 1, 1, 2, 5}, is not matching with what you mentioned. Could you please elaborate on the changes I need to make? I included this sorting example to illustrate that if I take more examples, the same steps should be followed. If you want, I can include some problems related to the priority queue.

**Comment by wingkwong** [comment]
I've seen different implementations with the same logic. Yours is exactly same as GFG one, as well as the test case. Speaking of test cases, I've no idea why you would add the below one. This case and code are not even from LC. The numbers are exactly matched with the GFG one.

```java
    public static void main(String[] args) {
        Solution solution = new Solution();
        int[] nums = {12, 11, 13, 5, 6, 7};
        System.out.println("Original Array: " + Arrays.toString(nums));
        solution.sortArray(nums);
        System.out.println("Sorted Array: " + Arrays.toString(nums));
    }
```

**Comment by i-am-SnehaChauhan** [comment]
I have made changes and removed that example. Could you please explain what other changes you would like me to make? Additionally, may I use problems based on the priority queue?

**Review by wingkwong — CHANGES_REQUESTED** [review]
1. not detailed enough. please add more details and diagrams to explain.
2. you haven't explained the code clearly. Even you walk through the steps but beginners may not understand how the code links to it.
3. This is mandatory: `I've explained my topic well with 2 - 3 LC problems and no external problems are used.`
4. add 2 more problems in suggested problems.

**Comment by wingkwong** [comment]
closing due to inactivity

**Pull request closed without merging**
