### PR TITLE
Added some good Problems related to Trie

### PR DESCRIPTION
**Pull request by sceary-expert**
These are the problems that one should definitely give a try. You might upload solution of these problems (which will be great if you do).

### CODE REVIEW

**Review by wingkwong — CHANGES_REQUESTED** [review]
Please follow this format.

https://github.com/wingkwong/leetcode-the-hard-way/blob/main/tutorials/basic-topics/arrays.md?plain=1#L79-L112

**Comment by vigneshshiv** [comment]
Assigned it to me, I will add it later.

**Comment by wingkwong** [comment]
@vigneshshiv You can make a new PR. If it's ok, then I'll close this one.

**Comment by vigneshshiv** [comment]
@wingkwong Please go ahead, I will raise a PR for this later.

**Comment by vigneshshiv** [comment]
Not yet, I will do it in 2 days. Can you hold this till then ?

**Comment by wingkwong** [comment]
Sure.

**Comment by vigneshshiv** [comment]
@wingkwong raised PR for trie related problems, #298 and #299. 

Please check once and let me know if any changes needed.

**Pull request closed without merging**
